### ISSUE TITLE
`several time frequencies` Error

### ISSUE THREAD

**Issue by BERENZ** [rOpenGov/eurostat#51] opened 2016-04-16 13:43 UTC
I've encountered the following error for the `cens_01rdhh` eurostat table

```
> cens_01rdhh <- get_eurostat(id = 'cens_01rdhh')
trying URL 'http://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&file=data%2Fcens_01rdhh.tsv.gz'
Content type 'application/octet-stream;charset=UTF-8' length 68495 bytes (66 KB)
==================================================
downloaded 66 KB

Error in tidy_eurostat(y_raw, time_format, select_time, stringsAsFactors = stringsAsFactors,  : 
  Data includes several time frequencies. Select frequency with
         select_time or use time_format = "raw".
         Available frequencies: '''1''2''3''4''5''6''0''7''8''9''A''B''C''D''E''F'
```
**EDIT**: `get_eurostat_json` works fine.

My session info:

```
> devtools::session_info()
Session info -------------------------------------------------------------
 setting  value                       
 version  R version 3.2.2 (2015-08-14)
 system   x86_64, darwin14.5.0        
 ui       RStudio (0.99.878)          
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Europe/Warsaw               
 date     2016-04-16                  

Packages -----------------------------------------------------------------
 package    * version     date       source                            
 assertthat   0.1         2013-12-06 CRAN (R 3.2.0)                    
 colorspace   1.2-6       2015-03-11 CRAN (R 3.2.0)                    
 curl         0.9.7       2016-04-10 CRAN (R 3.2.2)                    
 DBI          0.3.1       2014-09-24 CRAN (R 3.2.0)                    
 devtools     1.11.0      2016-04-12 CRAN (R 3.2.2)                    
 digest       0.6.9       2016-01-08 CRAN (R 3.2.2)                    
 dplyr      * 0.4.3       2015-09-01 CRAN (R 3.2.0)                    
 eurostat   * 1.2.21.9002 2016-04-16 Github (rOpenGov/eurostat@59205c3)
 ggplot2    * 2.1.0       2016-03-01 CRAN (R 3.2.2)                    
 ggthemes   * 3.0.3       2016-04-09 CRAN (R 3.2.2)                    
 git2r        0.14.0      2016-03-13 CRAN (R 3.2.2)                    
 gtable       0.2.0       2016-02-26 CRAN (R 3.2.2)                    
 htmltools    0.3.5       2016-03-21 CRAN (R 3.2.2)                    
 httr         1.1.0       2016-02-02 Github (hadley/httr@a68c86c)      
 knitr        1.12.3      2016-01-22 CRAN (R 3.2.2)                    
 labeling     0.3         2014-08-23 CRAN (R 3.2.0)                    
 lazyeval     0.1.10      2015-01-02 CRAN (R 3.2.0)                    
 lubridate  * 1.5.6       2016-04-06 CRAN (R 3.2.4)                    
 magrittr     1.5         2014-11-22 CRAN (R 3.2.0)                    
 memoise      1.0.0       2016-01-29 CRAN (R 3.2.2)                    
 munsell      0.4.3       2016-02-13 CRAN (R 3.2.2)                    
 plyr         1.8.3       2015-06-12 CRAN (R 3.2.0)                    
 R6           2.1.2       2016-01-26 CRAN (R 3.2.3)                    
 Rcpp         0.12.4      2016-03-26 CRAN (R 3.2.4)                    
 rmarkdown    0.9.5       2016-02-22 CRAN (R 3.2.2)                    
 scales       0.4.0       2016-02-26 CRAN (R 3.2.2)                    
 stringi      1.0-1       2015-10-22 CRAN (R 3.2.2)                    
 stringr      1.0.0       2015-04-30 CRAN (R 3.2.0)                    
 tidyr      * 0.4.1       2016-02-05 CRAN (R 3.2.2)                    
 withr        1.0.1       2016-02-04 CRAN (R 3.2.2)                    
 yaml         2.1.13      2014-06-12 CRAN (R 3.2.0)   
```

**Comment by pbiecek** [comment] 2016-04-16 13:50
The automagic guess for time failed,
but you could try the suggestion in the error message
```
cens_01rdhh <- get_eurostat(id = 'cens_01rdhh', time_format = "raw")
```

**Comment by BERENZ** [comment] 2016-04-16 14:01
Ok!

**Comment by antagomir** [comment] 2016-04-16 14:44
Thanks for reporting! It is perhaps better to have this error with a suggested fix in the error msg, rather than having the raw format as generic default unless someone comes with other suggestions. Hence closing the issue for now.

**Comment by jhuovari** [comment] 2016-04-18 07:02
This is actually a bug. The 'cens_01rdhh' does not include several time frequencies, actually only one year, so `tidy_eurostat` fails for some other reason.

I will look in to this.

**Comment by jhuovari** [comment] 2016-04-18 08:05
The problem is that the structure of the 'cens_01rdhh' and some other census data is different from normal eurostat data. Normally time variable is on column names. In this case the column forms the geo variable.

To fix this `tidy_eurostat´ should be done more general, so that it could parses time (and other) variable correctly regardless, where it is found. Or we could apply some dirty fix.

**Comment by antagomir** [comment] 2016-04-18 09:25
I vote for a proper fix if allowed by other time constraints..

**Closed** 2016-04-20 20:03 UTC

**Comment by jhuovari** [comment] 2016-04-20 20:04
Proper fix. Please test.

**Comment by antagomir** [comment] 2016-04-20 20:08
Ok CRAN build checks go through fine at least.
