### ISSUE TITLE
Install package error - Mac only?

### ISSUE THREAD

**Issue by saghirb** [rOpenGov/eurostat#196] opened 2020-11-20 11:15 UTC
I get `non-zero exit status` when trying to install the current CRAN version (3.6.83) of the `eurostat` package on MacOS (it installs fine on Linux or Windows). The error message is: 

```
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so, 6): Symbol not found: _EXTPTR_PTR
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so
  Expected in: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib
 in /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
````  

Reinstalling the `Rcpp` package does not make a difference.

Can anyone offer any pointers as to how to resolve this?

**Comment by Raquel-B** [comment] 2020-11-20 11:19
I have had the same issue since yesterday. I get Error:



**`Error in dyn.load(file, DLLpath = DLLpath, ...) :** 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/sf/libs/sf.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/sf/libs/sf.so, 6): Library not loaded: /usr/lib/libpq.5.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/sf/libs/sf.so
  Reason: image not found
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: **lazy loading failed for package ‘eurostat’**
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/eurostat’

The downloaded source packages are in
	‘/private/var/folders/kn/hmvr864x4kl3g_402fxjqlzc0000gn/T/Rtmpu3YBMV/downloaded_packages’


✔ Package 'eurostat' successfully installed.
Warning message:
In utils::install.packages("eurostat", repos = "https://cran.rstudio.com/") :
  **installation of package ‘eurostat’ had non-zero exit status`**

**Comment by Raquel-B** [comment] 2020-11-20 11:22
I have had the same issue since yesterday. I get Error:

```

Error in dyn.load(file, DLLpath = DLLpath, ...) :
unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/sf/libs/sf.so':
dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/sf/libs/sf.so, 6): Library not loaded: /usr/lib/libpq.5.dylib
Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/sf/libs/sf.so
Reason: image not found
Calls: ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘eurostat’

removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/eurostat’
The downloaded source packages are in
‘/private/var/folders/kn/hmvr864x4kl3g_402fxjqlzc0000gn/T/Rtmpu3YBMV/downloaded_packages’

✔ Package 'eurostat' successfully installed.
Warning message:
In utils::install.packages("eurostat", repos = "https://cran.rstudio.com/") :
installation of package ‘eurostat’ had non-zero exit status
```

**Comment by Raquel-B** [comment] 2020-11-20 11:23
I have had the same issue since yesterday. I get Error:

```
**Error in dyn.load(file, DLLpath = DLLpath, ...) :**
unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/sf/libs/sf.so':
dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/sf/libs/sf.so, 6): Library not loaded: /usr/lib/libpq.5.dylib
Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/sf/libs/sf.so
Reason: image not found
Calls: ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
**ERROR: lazy loading failed for package ‘eurostat’**

✔ Package 'eurostat' successfully installed.
Warning message:
In utils::install.packages("eurostat", repos = "https://cran.rstudio.com/") :
**installation of package ‘eurostat’ had non-zero exit status**
```

**Comment by antagomir** [comment] 2020-11-20 11:28
Not immediately certain what causes this. But the pkg went to CRAN just yesterday. Could it be that Mac builds are not yet available.

**Comment by antagomir** [comment] 2020-11-22 11:55
Is this still unresolved or was it temporary? At least the [CI with GHA](https://github.com/rOpenGov/eurostat/actions/runs/377227259) cheks go through with no prob also in Mac & Win.

**Comment by saghirb** [comment] 2020-11-22 18:07
I just tried it and it installed fine. Thanks @antagomir for the explanation :)

**Comment by Raquel-B** [comment] 2020-11-23 10:25
I installed it fine but am still getting an error when trying to use the Eurostat package

**Comment by antagomir** [comment] 2020-11-23 11:40
I am not sure what the problem is but if we are lucky, this might be resolved by rebooting and starting a fresh R session?

**Comment by Raquel-B** [comment] 2020-11-23 12:37
Yes! In addition to restarting the computer, I uninstalled and reinstalled eurostat, sf and Refmanager packages. Then eurostat package worked. Thank you @antagomir :)

**Comment by antagomir** [comment] 2020-11-23 12:44
Great! Thanks for letting us know. Citations to the R journal paper welcome!

**Closed by antagomir** 2020-11-23 12:44 UTC
